### PR TITLE
fix(bridge): harden /chat/history and /images across rollover (#197 #199 #201)

### LINKED ISSUE #197: list_images can return [] if a rollover deletes a globbed buffer between glob and read
## Summary
`list_images` (brain/bridge/server.py, `GET /images`) snapshots `buffers_dir.glob("*.jsonl")` then reads each file. If a rollover deletes a globbed old buffer before the read, `_read_jsonl_lines` yields zero rows silently (its `is_file()` guard), and the successor file — which does carry the `image_shas` — was not in the snapshot, so the response is `[]` for that call.

## Evidence
Reproduced by forced widening in the dragonfly hunt (hunts/bridge-order-pollution-flakes, O24: 8/8 live vs 0/8 with the supervisor stubbed). The natural window is sub-millisecond and the next call self-heals, so this is low priority; deferred from #196.

## Fix direction
Re-list once when a globbed file vanished, or read the successor via the `rolled_to` pointer.

### LINKED ISSUE #199: /chat/history paging cursor is not translated across a rollover redirect; resolved sid not echoed
## Summary
After #196, `GET /chat/history?session_id=<old>` follows the `rolled_to` pointer to the successor. Two known gaps, deliberately deferred:
1. `before_turn` is a synthetic line index computed against the buffer the renderer last saw; across a redirect it is applied to the successor's line index, so a paging call mid-rollover can return a different window under the same cursor.
2. `ChatHistoryResponse` does not echo the resolved sid, so the renderer cannot learn it was redirected (unlike `/chat`, which returns the resolved sid).

Renderer currently reloads from the top after a rollover, so (1) is latent. Fix: translate the cursor (or reset it on redirect) and add a `session_id` field to the response.

### LINKED ISSUE #201: _BUFFER_SESSION_ID_RE (server.py) duplicates _SESSION_ID_RE (buffer.py), kept in sync only by a comment
## Summary
`brain/bridge/server.py` re-declares the session-id grammar as `_BUFFER_SESSION_ID_RE` with a comment saying it must match `brain/ingest/buffer.py::_SESSION_ID_RE`. They are byte-identical today. If either drifts, `/chat/history`'s re-validation of a resolved successor (added in #196) silently falls back to the request sid, and `read_rolled_to` on a request sid the server accepted could raise.

Fix: import the one constant from `brain.ingest.buffer` (or expose a public name there). One-line change; nitpick from the #196 reviews.

### PR DESCRIPTION
**Pull request by hanamorix**
## Summary
Three small, verified-at-HEAD defects in `brain/bridge/server.py`'s history/images handlers, deferred from #196. One PR because they share the file and the rollover mechanism.

- **#199** `/chat/history` echoes the resolved `session_id` and resets `before_turn` on a rollover redirect (the cursor was an index into the old buffer). Renderer already reloads from the top after a rollover, so dropping the cursor serves the newest page, which is what it expects.
- **#197** `/images` re-globs once after the scan if any globbed buffer vanished, scanning only unscanned paths. Covers a vanish before *or during* the read. Dedupe is min-by-ts so the extra scan is safe.
- **#201** import `_SESSION_ID_RE` from `brain.ingest.buffer` instead of a duplicate literal.

## Verification
- Root causes re-read at HEAD, not taken from the triage summary.
- **Test-first**: 5 new tests red before the change (`KeyError: 'session_id'` ×3; images `[] == [sha]`; #201 source oracle). One pre-existing test updated for the new response field.
- Finding worth recording: an `is` identity test for #201 passed *before* the fix because `re.compile` caches identical patterns. The regression test is a source-level oracle instead.
- The first #197 fix (re-glob when `is_file()` is false before the read) did not catch a vanish during the read; the test exposed it and the fix was restructured to check after the scan.

## Gate
- `uv run pytest`: 4675 passed, 6 failed. Same 6 as `main` @ 880e2522 with no diff applied (2× live claude-cli OAuth/422 in the agent shell, 2× dangling local `.claude/skills/caveman*` symlinks, #205, #206). Not introduced here.
- `ruff check .` clean. `pnpm test` + `pnpm build` clean.

Not in scope: #198 (which GETs should hold the session busy) needs a design ruling first.

Closes #197
Closes #199
Closes #201

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by hanamorix** [comment]
Status note: the only failing CI check here is `test_threading_safety::test_chat_threaded_round_trip_no_silent_sqlite_drop`, which also fails on `main` (#206, stale since #167 merged). Fixed in #209. Once #209 lands and this branch takes main again, CI goes green. Branch is already merged up to `main` @ db0fec1a with no conflicts.
