### PR TITLE
fix(tests): drop retired recent_tones kwarg (main red on all 3 CI platforms)

### PR DESCRIPTION
**Pull request by hanamorix**
## Problem
CI test workflow is red on ubuntu/macos/windows since the #246 merge (runs 34725806641, 34773261993):

```
FAILED tests/unit/brain/engines/test_heartbeat_auth_deferred.py::test_voice_reflection_deferral_is_quiet
TypeError: run_voice_reflection_tick() got an unexpected keyword argument 'recent_tones'
```

## Cause
Merge-order collision between two PRs: #202 (`a20d82ba`) retired the `recent_tones` parameter of `run_voice_reflection_tick`; #246 (`a34e267d`) added a test written against the pre-#202 signature. Each PR was green on its own branch.

## Fix
Drop the kwarg from the one call site. No change under `brain/`. Verified: `grep -rn recent_tones tests/ brain/` is empty; the heartbeat + initiate test modules pass; ruff clean.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ThinkerOfThoughts** [comment]
Duplicate of #254, which is now merged to `main`. Both PRs make the identical one-line change (dropping the retired `recent_tones` kwarg from `test_voice_reflection_deferral_is_quiet`), so this one is now redundant against `main`. Moving it to draft; it can be closed.
