### PR TITLE
refactor(cadence): keep persisted cadence state under <persona>/cadence/ with legacy self-migration

### LINKED ISSUE #178: Consolidate the many single-entry cadence files into one cadence file (or a cadence/ subdirectory)
**Request:** each scheduling cadence is stored as its own tiny file at the persona-dir root (9 observed, each holding only a `{"next_at": ...}` timestamp). Consolidate them into a single cadence file with one entry per item, or group them under a dedicated `cadence/` subdirectory.
**Where it shows up:** the persona directory root — e.g. the maintenance, interest-sweep, finalize, log-rotation, initiate-review, voice-reflection, and compaction cadence files, plus the self_model and soul cadence/state files.
**Likely area:** the generic load/save helper in `brain/bridge/persisted_cadence.py` (7 files via the supervisor), plus two bespoke modules following the same one-file-per-item pattern (`brain/soul/cadence.py`, `brain/self_model/cadence.py`).

### PR DESCRIPTION
**Pull request by hanamorix**
## Summary
Nine single-entry `{"next_at": ...}`-style files sat at the persona root (verified: 7 via `persisted_cadence.py`, plus `soul_review_state.json` and `self_model_cadence_state.json`). They now live under `<persona>/cadence/`.

**Why a subdirectory, not one merged file:** ten independent writers each do an atomic temp-file + rename. Merging them into one JSON would replace ten atomic per-file writes with a shared read-modify-write hotspot across supervisor blocks, for no functional gain. Grouping keeps every existing invariant (fail-toward-running on missing/corrupt, atomic save, soul's backoff semantics) byte-for-byte.

**How:** one layer-neutral resolver, `brain.paths.cadence_state_path(persona_dir, filename)`:
- returns `<persona>/cadence/<filename>`;
- on first resolve, moves a legacy root-level `<persona>/<filename>` into place; never over an existing new file (legacy left alone rather than silently lost); best-effort, a failed move warns and the caller's missing-file handling (due-now) takes over.

`persisted_cadence._state_path`, `soul/cadence._state_path`, and `self_model/cadence._state_path` all route through it. Kindled-link's `tick_cadence.json` / `relationship_cadence.json` already lived under `kindled_link/` and are untouched.

Fixes #178

## §Wiring
- **Reads / feeds:** no change to any cadence's semantics or consumers; storage location only.
- **Fires on a live path:** yes; the existing `run_folded` through-path tests (`test_supervisor_cadence_persisted.py`, `test_supervisor_soul_cadence.py`) now assert the files are written under `cadence/`.

## §Deferred
- Renaming `soul_review_state.json` / `self_model_cadence_state.json` to a uniform `*_cadence.json`: not done, they carry extra fields (backoff) and a rename buys nothing.
- Reaping a stranded legacy file when the new one already exists: left for a human; the sidecar sweep in #193 does not cover it by design.

## Verification
- Resolver watched red (`ImportError: cannot import name 'cadence_state_path'`), then green (3 tests incl. migration + no-clobber).
- Integration fixtures updated to `cadence/` (17 sites across two files).
- Targeted: bridge + supervisor + soul + self_model: 506 passed. `ruff check` clean.
- Full suite under the CI marker filter posted as a comment when complete.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by hanamorix** [comment]
**Verification (local)** — full suite under the CI marker filter:

```
2 failed, 4593 passed, 6 skipped, 5 xfailed in 255s
```

The 2 failures are the #169 pair fixed in #188; this PR is based on that branch so its own checks run green.
